version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: search-the-point-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: search-the-point-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - WDS_SOCKET_PORT=0
      - ESLINT_NO_DEV_ERRORS=true
      - DISABLE_ESLINT_PLUGIN=true
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_uploads:
  backend_db:

networks:
  app-network:
    driver: bridge 